### ISSUE TITLE
代码结构

### ISSUE THREAD

**Issue by CrazyWalk** [nanchen2251/AiYaSchoolPush#1]
代码结构偏乱。
有些地方后期重构会很麻烦

**Comment by nanchen2251** [comment]
由于时间比较杂，所以这个只是一个练手的项目，供初学者学习使用，不提供商业用途~

**Comment by CrazyWalk** [comment]
我有个比较简单的建议，最好不要试图去弄一个TitleView。
国内app比较复杂。TitleView无法重用的。

**Comment by CrazyWalk** [comment]
还有，最好有模块化思想。这个对app设计会有很大的帮助

**Comment by nanchen2251** [comment]
嗯嗯，这个挺好的，后面不管是学习还是开发肯定会很多考虑的。
